### ISSUE TITLE
Not working in A14

### ISSUE THREAD

**Issue by frickypickle** [WindSpiritSR/CustomCACert#2]
Hello, 
I am using a Xiaomi 12, running Evolution-X offical based on Android 14. I did all the steps however I am not able to make my certificate as root. If there are any steps to troubleshoot/debug please let me know and I can try to help. I am trying to get requable working

**Comment by WindSpiritSR** [comment]
Already fixed, please update and reinstall

**Comment by frickypickle** [comment]
Yes it works, thanks a lot
